Hw 02
Albertukraine/nodejs-homework-rest-api pull request #1
Opened 2023-01-26 19:43 UTC by Albertukraine

перевірте пліз. Мирного неба та 220V 24/7 )))

2023-01-27 18:16 UTC, Eastvarga requested changes
Погана логіка, не вірна місцями, погана реалізація місцями.
Треба доопрацювати

2023-01-27 18:16 UTC, Eastvarga commented on app.js
> +  res.status(404).json({ message: 'укшгпдцшугкнапдцшуг ' })
Погана звичка!

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  console.log(data);
не повинно бути консолей у робочому коді

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  return gottenContact;
чому взятиКонтакт повертає масив?? Так у співпадінні буде один елемент отримайте його деструктивним примвоєнням та повертайтне вже сам елемент а не масив!

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  const contactList = JSON.parse(data);
function listContacts() перевикористовуйте вже існуючу функцію

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  const contactList = JSON.parse(data);
Теж саме для отримання списку контактів з файлу перевикористайте вже існуючу функцію async function listContacts()

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  console.log("indexOfContact", indexOfContact);
ніяких консолей у робочому коді

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  await contactList.splice(indexOfContact, 1);
а це що таке? метод масиву не є промісом

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  await fs.writeFile(contactsPath, JSON.stringify(contactList));
отже Ви записали той самий масив що взяли з файлу, а як же видалення елементу?

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  const contactList = JSON.parse(data);
теж саме

2023-01-27 18:16 UTC, Eastvarga commented on models/contacts.js
> +  contactToUpdate.phone = body.phone;
для PUT та з робочою валідцією підійде, але це погана реалізація
простіше
let updatedContact 
const updatedArray = contactList.map( (contact)=>{
if(contact.id===contactId){ updatedContact ={...contact, ...body} return updatedContact  } return contact} )
щось таке

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  email: Joi.string().email({ minDomainSegments: 2, tlds: { allow: ['com', 'net', 'uk', 'ua'] } }),
Відсутня обов'язковість поля телефону у схемі

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +const contactSchema = Joi.object({
Винесіть схему валідації до файлу схем валідації, та саму валідацію до мідлварів, не повинна валідація бути у коді бізнеслогіки (контроллері\сервісі)

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +      code: 200,
res.status(200).json(contacts) достатньо,
Не потрібна зайва інформація та зайві складнощі у відповіді

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  const contact = await getContactById(id);
Добре, але зараз тут чомусь масив повертається, а це вже не добре - зауваження вище

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +      throw error;
Валідацію винесіть у мідлвар та використовуйте його до контроллера

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +      },
Достатньо  res.status(201).json(result) - це поверне сам елемент

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  return}
Це зовсім зайве - подивіться уважно що робіть функція відалення, та помилку кидати повина вона

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  await removeContact(id);
ось цей метод повинен повертати видалений контакт або нічого, та якщо нічого тоді кидаєте помилку що єлемент не знайдено

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.status(200).json({ message: `Contact with id ${id} was deleted from contact list` });
краще повертати у відповіді сам видалений елемент

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  return};
теж саме, зайва функція getContactById, достатньо функції апдейту для цього

2023-01-27 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +      result,
Після апдейту повертаєте елемент який був до апдейту? Дивна логіка

2023-01-27 18:56 UTC, Albertukraine commented on app.js
> +  res.status(404).json({ message: 'укшгпдцшугкнапдцшуг ' })
Погоджуюсь

2023-01-27 18:57 UTC, Albertukraine commented on models/contacts.js
> +  console.log(data);
і я ж це знаю. Чисто неуважність.

2023-01-27 18:57 UTC, Albertukraine commented on models/contacts.js
> +  return gottenContact;
виправив

2023-01-27 19:11 UTC, Albertukraine commented on models/contacts.js
> +  const contactList = JSON.parse(data);
слушне зауваження, спрацювало.

2023-01-27 19:25 UTC, Albertukraine commented on models/contacts.js
> +  await contactList.splice(indexOfContact, 1);
await прибрав - це перекочувало з попередньої ДЗ.

2023-01-27 19:32 UTC, Albertukraine commented on models/contacts.js
> +  await fs.writeFile(contactsPath, JSON.stringify(contactList));
як я розумію метод splice мутує масив. тому перезаписує вже із видаленим елементом. чи треба спершу видалити все із файлу перед тим, як туди покласти оновлений масив?

2023-01-27 19:34 UTC, Albertukraine commented on models/contacts.js
> +  const contactList = JSON.parse(data);
перевикористав listContacts()

2023-01-27 19:39 UTC, Albertukraine commented on routes/api/contacts.js
> +  email: Joi.string().email({ minDomainSegments: 2, tlds: { allow: ['com', 'net', 'uk', 'ua'] } }),
так розумію що мали на увазі поле емейл, бо телефон має у схемі .required() ( схему емейл виправив )

2023-01-27 19:45 UTC, Albertukraine commented on routes/api/contacts.js
> +  const contact = await getContactById(id);
деструкурував в функціі getContactById - повертається об'єкт відтепер

2023-01-27 19:54 UTC, Albertukraine commented on routes/api/contacts.js
> +      },
виправив цей рядок і логіку, бо саме вона повертала весь оновлений список контактів, а не оновлений елемент.

2023-01-27 20:09 UTC, Albertukraine commented on routes/api/contacts.js
> +  await removeContact(id);
додав перевірку в метод, який повертає null якщо нема підходящого індексу для видалення. Далі вже ясно що якщо нема що видаляти - викидає помилку.

2023-01-28 11:29 UTC, Albertukraine commented on routes/api/contacts.js
> +  res.status(200).json({ message: `Contact with id ${id} was deleted from contact list` });
виправив

2023-01-28 11:35 UTC, Albertukraine commented on routes/api/contacts.js
> +      result,
виправив. повертає апдейтнутий контакт.

2023-01-28 11:45 UTC, Albertukraine commented on routes/api/contacts.js
> +  return};
зробив перевірку всередині логіки, яка викидає помилку.

2023-01-28 11:46 UTC, Albertukraine commented on routes/api/contacts.js
> +  return}
перевірка відбувається всередині функціі deleteContact - цієї фігні позбавився

2023-01-28 12:09 UTC, Albertukraine commented on models/contacts.js
> +  contactToUpdate.phone = body.phone;
дійсно, так краще - можна оновлювати дані кожного поля окремо.  Дякую за підказку.

2023-01-28 16:55 UTC, Albertukraine commented on routes/api/contacts.js
> +const contactSchema = Joi.object({
виніс

2023-01-29 10:07 UTC, Eastvarga approved these changes

2023-01-29 10:07 UTC, merged