Hw03 mongodb
Albertukraine/nodejs-homework-rest-api pull request #2
Opened 2023-02-05 22:48 UTC by Albertukraine

вітаю. перевірте пліз. не второпав навіщо по ТЗ треба робити окрему функцію для апдейту статусу контакта, якщо можа було б перевикористати попередню - апдейтКонтакт. Також помітив що завдяки схемі моделі статус фафорит - фолс по дефолту присвоюється звідти.

2023-02-06 18:09 UTC, Eastvarga requested changes
Є багато зауважень.

2023-02-06 18:09 UTC, Eastvarga commented on controllers/contacts.js
> +  return data;
Це зайве достатньо повертати контакти навіть пустий масив - if (data.length === 0) {return null}; це зайве зовсім

2023-02-06 18:09 UTC, Eastvarga commented on controllers/contacts.js
> +const contactToDelete = await Contact.remove({_id: contactId});
є більш доцільний метод, findByIdAndRemove

2023-02-06 18:09 UTC, Eastvarga commented on controllers/contacts.js
> +if (contactToDelete.length === 0) {return null};
теж зайва перевірка

2023-02-06 18:09 UTC, Eastvarga commented on controllers/contacts.js
> +if(!contactToUpdate) {return null};
зайве

2023-02-06 18:09 UTC, Eastvarga commented on controllers/contacts.js
> +if (!contactToUpdate) {return null};
теж зайве

2023-02-06 18:09 UTC, Eastvarga commented on db/connectDatabase.js
> +
чому не додали у змінні середовища?
усі ключі повинні бути у файлі .env та ініціалізуватись через файл конфігурацій.

2023-02-06 18:09 UTC, Eastvarga commented on routes/api/contacts.js
> +    };
Для цього є схема валідації, де вона? Чому не користуєтесь схемою валідації -  Joy наприклад?

2023-02-06 19:26 UTC, Albertukraine commented on controllers/contacts.js
> +  return data;
прибрав

2023-02-06 19:27 UTC, Albertukraine commented on controllers/contacts.js
> +const contactToDelete = await Contact.remove({_id: contactId});
виправив на findByIdAndRemove

2023-02-06 19:30 UTC, Albertukraine commented on controllers/contacts.js
> +if (contactToDelete.length === 0) {return null};
перевірку прибрав

2023-02-06 19:32 UTC, Albertukraine commented on controllers/contacts.js
> +if(!contactToUpdate) {return null};
прибрав

2023-02-06 19:33 UTC, Albertukraine commented on controllers/contacts.js
> +if (!contactToUpdate) {return null};
прибрав

2023-02-06 19:55 UTC, Albertukraine commented on db/connectDatabase.js
> +
переніс в файл .env 
сам файл вніс у лист гітігнору
поставив пакет dotenv
викликав метод dotenv.config();

2023-02-06 20:38 UTC, Albertukraine commented on routes/api/contacts.js
> +    };
Це прибираю. Схему валідаціі додав. Але валідація ( у разі відсутності рядку із ФАВОРІТ ) видає свій месседж помилки, а за умовою завдання маю вивести месседж "missing field favorite" і помилку 400. Якщо валідація (мідлвар) не пропускає запрос далі, а зупиняється на мідлварі, то де я можу присвоїти статус 400 і саме цей месседж?

2023-02-07 17:40 UTC, Eastvarga commented on routes/api/contacts.js
> +    };
Помилку повинні віддавати ту, що є у валідації - "missing field favorite" і помилку 400 - це приклад помилки валідації

2023-02-07 17:46 UTC, Albertukraine commented on routes/api/contacts.js
> +    };
Валідація JOY віддає "message": "\"favorite\" is required"

2023-02-07 17:49 UTC, Eastvarga requested changes
Є зауваження

2023-02-07 17:49 UTC, Eastvarga commented on routes/api/contacts.js
> +router.patch("/:contactId", validation(statusSchema), async (req, res, next) => {
забули що треба @ PATCH / api / contacts /: contactId / **favorite** - будьте уважніше

2023-02-07 17:49 UTC, Eastvarga commented on schemas/status.js
> +  favorite: Joi.boolean().required()
У валідатора є можливість конфігурувати тексти сповіщення, у Вас багато запитань через низький рівень знань про валідацію та валідатори, Завжди пробуйте шукати приклади у гуглі.

2023-02-07 17:52 UTC, Albertukraine commented on routes/api/contacts.js
> +router.patch("/:contactId", validation(statusSchema), async (req, res, next) => {
так, це прогледів. Дякую.

2023-02-07 19:13 UTC, Eastvarga approved these changes

2023-02-07 19:14 UTC, merged