Hw04 auth
Albertukraine/nodejs-homework-rest-api pull request #3
Opened 2023-02-14 23:56 UTC by Albertukraine

Вітаю. Довелося трохи відрефакторити попередній "паттерн", розділив контроллери по файлах і вже після робив із логіном юзера маніпуляціі.

2023-02-15 19:10 UTC, Eastvarga requested changes
Є невелике зауваження

2023-02-15 19:10 UTC, Eastvarga commented on middlewares/auth.js
> +    if (bearer !== "Bearer") {
чому токен не перевіряєтена невизначеність?

2023-02-16 08:27 UTC, Albertukraine commented on middlewares/auth.js
> +    if (bearer !== "Bearer") {
Провтикав. Нема зрозумілого пояснення. Виправляю.

2023-02-16 17:08 UTC, Eastvarga approved these changes

2023-02-16 17:08 UTC, Eastvarga commented on schemas/user.js
> +});
не потрібно дублювати код, просто перевикористайте вже існуючу схему реєстрації

2023-02-16 17:08 UTC, merged