Hw05 avatars
Albertukraine/nodejs-homework-rest-api pull request #4
Opened 2023-02-27 21:00 UTC by Albertukraine

Вітаю. Затестив, аватарку грузить і перетискає в 250х250.

2023-02-28 18:24 UTC, Eastvarga requested changes
Є зауваження.

2023-02-28 18:24 UTC, Eastvarga commented on controllers/users/updateAvatar.js
> +    const avatarURL = path.join("public", "avatars", avatarName);
невірно, не використовуйте модуль path для генерації URL строки
\`http://localhost:${PORT}/avatars/${avatarName}` - ось простий та вірний спосіб

2023-02-28 19:54 UTC, Albertukraine commented on controllers/users/updateAvatar.js
> +    const avatarURL = path.join("public", "avatars", avatarName);
дійсно, і він набагато легше читається. Дякую, виправив. Додав номер порту в налаштування ENV також, щоб звідти його отримувати усюди. Перевірив - працює!

2023-03-01 18:32 UTC, Eastvarga approved these changes

2023-03-01 18:32 UTC, merged